version: '3.1'

services:
    backend:
      build: ./backend
      environment:
        - PORT=5000
      restart: unless-stopped
    frontend:
      build: ./frontend
      environment:
        - PORT=3000
networks:
  default:
    external:
      name: felicity_nw